/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DriverPerformanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "evaluatePerformance"
      | "getDriverOrderCount"
      | "getPerformanceResult"
      | "owner"
      | "protocolId"
      | "setTargetThreshold"
      | "submitOrderCount"
      | "targetThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCountSubmitted"
      | "PerformanceEvaluated"
      | "TargetThresholdUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "evaluatePerformance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDriverOrderCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPerformanceResult",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setTargetThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitOrderCount",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "targetThreshold",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "evaluatePerformance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDriverOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPerformanceResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTargetThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitOrderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "targetThreshold",
    data: BytesLike
  ): Result;
}

export namespace OrderCountSubmittedEvent {
  export type InputTuple = [driver: AddressLike, submitter: AddressLike];
  export type OutputTuple = [driver: string, submitter: string];
  export interface OutputObject {
    driver: string;
    submitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PerformanceEvaluatedEvent {
  export type InputTuple = [driver: AddressLike];
  export type OutputTuple = [driver: string];
  export interface OutputObject {
    driver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetThresholdUpdatedEvent {
  export type InputTuple = [
    oldThreshold: BigNumberish,
    newThreshold: BigNumberish
  ];
  export type OutputTuple = [oldThreshold: bigint, newThreshold: bigint];
  export interface OutputObject {
    oldThreshold: bigint;
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DriverPerformance extends BaseContract {
  connect(runner?: ContractRunner | null): DriverPerformance;
  waitForDeployment(): Promise<this>;

  interface: DriverPerformanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  evaluatePerformance: TypedContractMethod<
    [driver: AddressLike],
    [string],
    "nonpayable"
  >;

  getDriverOrderCount: TypedContractMethod<
    [driver: AddressLike],
    [string],
    "view"
  >;

  getPerformanceResult: TypedContractMethod<
    [driver: AddressLike],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  setTargetThreshold: TypedContractMethod<
    [_newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitOrderCount: TypedContractMethod<
    [
      driver: AddressLike,
      encryptedOrderCount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  targetThreshold: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "evaluatePerformance"
  ): TypedContractMethod<[driver: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getDriverOrderCount"
  ): TypedContractMethod<[driver: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPerformanceResult"
  ): TypedContractMethod<[driver: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setTargetThreshold"
  ): TypedContractMethod<[_newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitOrderCount"
  ): TypedContractMethod<
    [
      driver: AddressLike,
      encryptedOrderCount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "targetThreshold"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "OrderCountSubmitted"
  ): TypedContractEvent<
    OrderCountSubmittedEvent.InputTuple,
    OrderCountSubmittedEvent.OutputTuple,
    OrderCountSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "PerformanceEvaluated"
  ): TypedContractEvent<
    PerformanceEvaluatedEvent.InputTuple,
    PerformanceEvaluatedEvent.OutputTuple,
    PerformanceEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "TargetThresholdUpdated"
  ): TypedContractEvent<
    TargetThresholdUpdatedEvent.InputTuple,
    TargetThresholdUpdatedEvent.OutputTuple,
    TargetThresholdUpdatedEvent.OutputObject
  >;

  filters: {
    "OrderCountSubmitted(address,address)": TypedContractEvent<
      OrderCountSubmittedEvent.InputTuple,
      OrderCountSubmittedEvent.OutputTuple,
      OrderCountSubmittedEvent.OutputObject
    >;
    OrderCountSubmitted: TypedContractEvent<
      OrderCountSubmittedEvent.InputTuple,
      OrderCountSubmittedEvent.OutputTuple,
      OrderCountSubmittedEvent.OutputObject
    >;

    "PerformanceEvaluated(address)": TypedContractEvent<
      PerformanceEvaluatedEvent.InputTuple,
      PerformanceEvaluatedEvent.OutputTuple,
      PerformanceEvaluatedEvent.OutputObject
    >;
    PerformanceEvaluated: TypedContractEvent<
      PerformanceEvaluatedEvent.InputTuple,
      PerformanceEvaluatedEvent.OutputTuple,
      PerformanceEvaluatedEvent.OutputObject
    >;

    "TargetThresholdUpdated(uint32,uint32)": TypedContractEvent<
      TargetThresholdUpdatedEvent.InputTuple,
      TargetThresholdUpdatedEvent.OutputTuple,
      TargetThresholdUpdatedEvent.OutputObject
    >;
    TargetThresholdUpdated: TypedContractEvent<
      TargetThresholdUpdatedEvent.InputTuple,
      TargetThresholdUpdatedEvent.OutputTuple,
      TargetThresholdUpdatedEvent.OutputObject
    >;
  };
}
